# Generated by Django 4.1.3 on 2022-11-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
